### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by rhuang91** [nielsrhansen/lsgl#1]
Hi Niel,

Thanks for your nice package lsgl. I am using your package to do some data analysis and I encountered an error when running your airline ticket price example. When I used the lsgl::cv() function it returned:
Error in get(paste(module_name, "sgl_lambda", "R", sep = "_"), asNamespace(PACKAGE)) : 
  object 'lsgl_xd_yd_sgl_lambda_R' not found
Would you please take a look and help me to work it out? I am using lsgl version 1.3.7 and sglOptim 1.3.7.

Thank you so much!

Rui

**Comment by nielsrhansen** [comment]
Dear Rui,

Thanks a lot for your feedback. I have fixed the problem. 

In fact, the package didn't work at all due to changes in sglOptim that were never reflected in lsgl. I believe I have made all necessary updates to lsgl, but if you encounter any further problems please report them.

Best, Niels

**Comment by rhuang91** [comment]
Hi Niels,

Thank you so much for your kind help! The new version works perfectly!

Best,

Rui

发件人: nielsrhansen<mailto:notifications@github.com>
发送时间: Thursday, December 20, 2018 8:57 PM
收件人: nielsrhansen/lsgl<mailto:lsgl@noreply.github.com>
抄送: Huang, Rui<mailto:rui-huang-2@uiowa.edu>; Author<mailto:author@noreply.github.com>
主题: Re: [nielsrhansen/lsgl] Error report (#1)


Dear Rui,

Thanks a lot for your feedback. I have fixed the problem.

In fact, the package didn't work at all due to changes in sglOptim that were never reflected in lsgl. I believe I have made all necessary updates to lsgl, but if you encounter any further problems please report them.

Best, Niels

―
